name: Tests

on:
    push:
        branches:
            - main
            - master
        tags:
            - "v*"
    pull_request:

jobs:
    format:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v7
            - run: npm ci
            - run: npm run format && git diff --exit-code

    test:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v7
            - run: npm ci
            - run: npm run test
